### PR TITLE
Update `action.yml` with `pull_request` instead of `pull_number`

### PR DESCRIPTION
**Pull request by drazenbuljovcic**
Hi, in the readme, the `pull_request` prop is not right, as in the code the `pull_number` property is used for this configuration. This small PR updates the docs.

### CODE REVIEW

**Comment by nbrugger-tgm** [comment]
Hi, thank you for reaching out!

Regarding to the code it is `pull_request`: https://github.com/nbrugger-tgm/merge-pr-action/blob/aff51ea6f9350712b39e6001e67ef4a00a7200e2/src/main.ts#L43  (which i would prefere) i think the place it is wrong is the `action.yml`.

Would you mind updating your PR so the use of `pull_request` over `pull_number` is unified?

**Comment by drazenbuljovcic** [comment]
Hey, yeah I did use `pull_request` as the docs say, but the validation wasn't right!
image

I see, I will change the action.yml file in that case!
Thanks for pointing that out!

**Comment by nbrugger-tgm** [comment]
I think this will also resolve the issue with "pr not found" as gh action most likely didn't forwarded you value. If the repo that uses my action is public feel fre to send me the run link so i can investigate

**Review by nbrugger-tgm — APPROVED** [review]

**Comment by drazenbuljovcic** [comment]
I pushed the change to `action.yml`.
The validations were failing only because the attributes passed down to the action were not valid (but it is only the warning though).

I am opening a pr automatically using another gh action in the previous step and using the outputs of it for this step.
Even if it resolves later correctly, it might not pick up this PR as open, maybe it's a race condition.
image

**Comment by drazenbuljovcic** [comment]
I will merge this PR to test the change without the warning, if the error persists, maybe it's related to the previous action outputs..

**Comment by nbrugger-tgm** [comment]
Your issue is actually related to a bug/edge case i did not thought about : https://github.com/nbrugger-tgm/merge-pr-action/pull/9

Using v0.2.2 should work for you

**Comment by nbrugger-tgm** [comment]
#### Release  [`0.2.2`](https://github.com/nbrugger-tgm/merge-pr-action/releases/tag/v0.2.2) should fix your issue

Also there is more informative logging, so it tells you more detailed what it does

**Comment by drazenbuljovcic** [comment]
It works amazing now!
Thank you for your help for helping!

**Pull request merged**
